### ISSUE TITLE
IOS 9.0 JotTouchSDK bitcode not enabled

### ISSUE THREAD

**Issue by antoniov72** [Adonit/Adonit-iOS-SDK#33]
We are compiling IOS 9.0 Xcode 7 and bitcode link error is raised due to bitcode App requirement. Will it be included in the next version of the SDK?

"You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE)"

thanks!

**Comment by jjxtra** [comment]
This is resolved with latest code.
