### ISSUE TITLE
Connect manually

### ISSUE THREAD

**Issue by octalflow** [Adonit/Adonit-iOS-SDK#39]
Hello.
Under SDK v3.2
I can not use storyboard.
So I just want to connect to a stylus manually.

JotStylusManager *jm = [JotStylusManager sharedInstance];
[jm enable];
[jm startDiscoveryWithCompletionBlock:^(BOOL success, NSError *error) {
			printf("OK success = %d\n", success);
		}];
above code just crashed.
[__NSCFString jotModelValue]: unrecognized selector sent to instance 0x17d959a0

Is this possible ?

**Comment by adonitDevel** [comment]
Hello octalflow,

Thank you for your query. 

1) This should not be the case, our program should still work even without a storyboard.
Provided, the stylus tip should be pressed during the connection process.
We experimented on this and our program went well without issues.

Could it be because you didn't properly initialize the SDK prior to connection?
Please reference our sample project code, under ViewController->viewDidLoad(), there
are some init functions that must be called prior to connection.

https://github.com/Adonit/Adonit-iOS-SDK/tree/master/JotTouchExample

2) Can you give us more details about your implementations? 
Please feel free to email us for more queries. 
We will be very happy to troubleshoot with you.

Cheers,
AdonitDevel
developers@adonit.net

**Comment by octalflow** [comment]
Thank you for your answer.

// xcode 8.0, iOS 10.0 SDK
I'm using cocos2d-x(3.8) and I don't know Objective-C well.

this is my main.

int main(int argc, char *argv[]) {
    NSAutoreleasePool * pool = [[NSAutoreleasePool alloc] init];

	int retVal = UIApplicationMain(argc, argv,
								   NSStringFromClass([JotDrawingApplication class]),
								   NSStringFromClass([AppController class]));
    [pool release];
    return retVal;
}


In my viewDidLoad,

UIViewController<JotModelController> *ptr = [UIStoryboard instantiateJotViewControllerWithIdentifier:JotViewControllerUnifiedStatusButtonAndConnectionAndSettingsIdentifier];

the above code just crashed.

Unknown class JotConnectionStatusViewController in Interface Builder file.
2016-10-21 12:34:41.794853 test[6377:4707293] -[UIViewController setShowBluetoothAlert:]: unrecognized selector sent to instance 0x14e349c0
2016-10-21 12:34:41.795507 test[6377:4707293] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIViewController setShowBluetoothAlert:]: unrecognized selector sent to instance 0x14e349c0'

libc++abi.dylib: terminating with uncaught exception of type NSException



So I did as below.

UIViewController<JotModelController> *ptr =
[[UIViewController<JotModelController> alloc]initWithNibName:JotViewControllerUnifiedStylusConnectionAndSettingsIdentifier bundle:nil];
// ptr is not null.
[self addChildViewController:ptr];
JotStylusManager *jm = [JotStylusManager sharedInstance];
jm.jotStrokeDelegate = self;
[jm enable];
[jm startDiscoveryWithCompletionBlock:^(BOOL success, NSError *error) {
	NSLog(@"Stylus Connected");
}];
	

the above code did not crashed but nothing happened.
Currently I linked SDK bundle.
I don't want to use SDK UI.
DO I MUST link SDK bundle ?

**Comment by octalflow** [comment]
I did add other link option(force_load)
I can use instantiateJotViewControllerWithIdentifier:JotViewControllerUnifiedStatusButtonAndConnectionAndSettingsIdentifier now.

**Comment by octalflow** [comment]
Thank you for your answer.

// xcode 8.0, iOS 10.0 SDK
I'm using cocos2d-x(3.8) and I don't know Objective-C well.

this is my main.

int main(int argc, char *argv[]) {

    NSAutoreleasePool * pool = [[NSAutoreleasePool alloc] init];


int retVal = UIApplicationMain(argc, argv,

  NSStringFromClass([JotDrawingApplication class]),

  NSStringFromClass([AppController class]));

    [pool release];

    return retVal;

}


In my viewDidLoad,

UIViewController<JotModelController> *ptr = [UIStoryboard
instantiateJotViewControllerWithIdentifier:
JotViewControllerUnifiedStatusButtonAndConnectionAndSettingsIdentifier];


the above code just crashed.


*Unknown class JotConnectionStatusViewController in Interface Builder file.*

*2016-10-21 12:34:41.794853 test[6377:4707293] -[UIViewController
setShowBluetoothAlert:]: unrecognized selector sent to instance 0x14e349c0*

*2016-10-21 12:34:41.795507 test[6377:4707293] *** Terminating app due to
uncaught exception 'NSInvalidArgumentException', reason:
'-[UIViewController setShowBluetoothAlert:]: unrecognized selector sent to
instance 0x14e349c0'*


*libc++abi.dylib: terminating with uncaught exception of type NSException*



*So I did as below.*


UIViewController<JotModelController> *ptr =

[[UIViewController<JotModelController>
alloc]initWithNibName:JotViewControllerUnifiedStylusConnectionAndSettingsIdentifier
bundle:nil];

// ptr is not null.

[self addChildViewController:ptr];

JotStylusManager *jm = [JotStylusManager sharedInstance];

jm.jotStrokeDelegate = self;

[jm enable];

[jm startDiscoveryWithCompletionBlock:^(BOOL success, NSError *error) {

NSLog(@"Stylus Connected");

}];



the above code did not crashed but nothing happened.
Currently I linked SDK bundle.
I don't want to use SDK UI.
DO I MUST link SDK bundle ?

thank you.



2016-10-20 15:44 GMT+09:00 adonitDevel <notifications@github.com>:
